---
  host: 0.0.0.0
  port_in: 30010
  port_out: 30011
  poll_ms: 500
  clients:
    - host: 127.0.0.1
      port: 30001
  pins:
    - pin: 18
      io: Writeable
      state: false
    - pin: 17
      io: Readable
      state: false
...
